<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>En_Admin_Reporting_Infrastructure_Layer</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\En-Admin-Reporting-Domain-Layer\En-Admin-Reporting-Domain-Layer.csproj" />
  </ItemGroup>

</Project>
